#!/usr/bin/env python3
"""Single source of truth for the PsychDeep mark.

The mark is a circle of concentric wave curves: the app's own wave metaphor,
folded into a disc. It is both the application logo and, in the patient's Ola
window, the breathing pacer itself — the same geometry, animated by the phase
the pacer is already tracking.

Running this script regenerates, from the constants below:

  frontend/public/icons/logo.svg            master, 13 curves (headers, docs)
  frontend/public/favicon.svg               compact, 7 curves, thicker stroke
  frontend/public/icons/icon-192.png        PWA / apple-touch
  frontend/public/icons/icon-512.png        PWA
  frontend/public/icons/icon-maskable-512.png  PWA maskable safe zone
  frontend/src/components/markGeometry.generated.ts   the same curves for React

Nothing else derives the geometry, so the animated mark in the UI and the
static icons can never drift apart.

    python3 frontend/scripts/generate_mark_assets.py
"""

from __future__ import annotations

import math
import pathlib

import cairosvg

# --- constants ---------------------------------------------------------
# Palette is the app's, not the mark's: #0f1419 is the served theme-color and
# the wave gradient is the one WavePage already paints.
INK = "#0f1419"
STOPS = [("0%", "#7fd8c2"), ("46%", "#6c98f4"), ("100%", "#2f4f9e")]

VIEW = 64.0
CENTER = VIEW / 2
RADIUS = 29.0          # clipping disc
WAVELENGTH = 32.0
AMPLITUDE = 2.6        # crest height of the equator curve

MASTER_COUNT = 13      # optically right above ~64px
MASTER_SPAN = 26.0
COMPACT_COUNT = 7      # below that the master fills in; fewer, thicker curves
COMPACT_SPAN = 22.0
MASTER_STROKE = 1.9
COMPACT_STROKE = 3.2

ROOT = pathlib.Path(__file__).resolve().parents[1]


def curves(count: int, span: float) -> list[dict]:
    """One wave curve per band, from the top of the disc to the bottom."""
    out = []
    half = (count - 1) / 2
    for i in range(count):
        t = (i - half) / half              # -1 (top) .. 0 (equator) .. 1 (bottom)
        y = CENTER + t * span
        # The wave is tallest at the equator and flattens toward the poles,
        # which is what makes the disc read as a sphere rather than a stack.
        amp = AMPLITUDE * math.cos(t * math.pi / 2)
        phase = t * math.pi * 0.12
        # Travel on inhale: outward from the core, inner bands further than
        # outer ones. That difference is what reads as depth instead of scale.
        shift = math.copysign(0.35 + 0.65 * (1 - abs(t)), t) if t else 0.0
        out.append(
            {
                "d": path(y, amp, phase),
                "shift": round(shift, 3),
                "opacity": round(0.62 + 0.38 * (1 - abs(t)), 3),
            }
        )
    return out


def path(y: float, amp: float, phase: float) -> str:
    """A sine drawn crest-to-trough as cubics, wide enough that clipping
    never exposes an end."""
    step = WAVELENGTH / 2
    start = -8.0 - phase / (2 * math.pi) * WAVELENGTH
    nodes = []
    x, k = start, 0
    while x < VIEW + 8 + step:
        nodes.append((x, y + amp * (1 if k % 2 == 0 else -1)))
        x, k = x + step, k + 1
    d = f"M {nodes[0][0]:.2f} {nodes[0][1]:.2f}"
    for (x0, y0), (x1, y1) in zip(nodes, nodes[1:]):
        d += f" C {x0 + step / 3:.2f} {y0:.2f}, {x1 - step / 3:.2f} {y1:.2f}, {x1:.2f} {y1:.2f}"
    return d


def svg(count: int, span: float, stroke: float, *, uid: str, ground: bool, scale: float = 1.0) -> str:
    stops = "".join(f'<stop offset="{o}" stop-color="{c}"/>' for o, c in STOPS)
    body = "".join(
        f'<path d="{c["d"]}" opacity="{c["opacity"]}"/>' for c in curves(count, span)
    )
    inset = (VIEW - VIEW * scale) / 2
    plate = f'<rect width="{VIEW}" height="{VIEW}" rx="{VIEW * 0.22:.1f}" fill="{INK}"/>' if ground else ""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VIEW:.0f} {VIEW:.0f}" '
        f'role="img" aria-label="PsychDeep">'
        f'<defs>'
        f'<linearGradient id="{uid}g" gradientUnits="userSpaceOnUse" x1="0" y1="3" x2="0" y2="61">{stops}</linearGradient>'
        f'<clipPath id="{uid}c"><circle cx="{CENTER}" cy="{CENTER}" r="{RADIUS}"/></clipPath>'
        f'</defs>'
        f'{plate}'
        f'<g transform="translate({inset:.2f} {inset:.2f}) scale({scale})">'
        f'<g clip-path="url(#{uid}c)" fill="none" stroke="url(#{uid}g)" '
        f'stroke-width="{stroke}" stroke-linecap="round">{body}</g>'
        f'</g>'
        f'</svg>'
    )


def ts() -> str:
    def block(name: str, count: int, span: float) -> str:
        rows = "\n".join(
            f'  {{ d: "{c["d"]}", shift: {c["shift"]}, opacity: {c["opacity"]} }},'
            for c in curves(count, span)
        )
        return f"export const {name}: MarkCurve[] = [\n{rows}\n];\n"

    return (
        "// GENERATED by frontend/scripts/generate_mark_assets.py — do not edit.\n"
        "// Run the script instead, so the animated mark and the PNG icons stay\n"
        "// the same drawing.\n\n"
        "export interface MarkCurve {\n"
        "  /** Path data in the 0 0 64 64 mark viewBox. */\n"
        "  d: string;\n"
        "  /** Outward travel on inhale, -1..1, scaled by --pd-mark-travel. */\n"
        "  shift: number;\n"
        "  opacity: number;\n"
        "}\n\n"
        f"export const MARK_VIEWBOX = \"0 0 {VIEW:.0f} {VIEW:.0f}\";\n"
        f"export const MARK_CLIP = {{ cx: {CENTER}, cy: {CENTER}, r: {RADIUS} }};\n"
        f"export const MARK_STOPS: Array<[string, string]> = "
        f"{[list(s) for s in STOPS]};\n".replace("'", '"')
        + f"export const MASTER_STROKE = {MASTER_STROKE};\n"
        f"export const COMPACT_STROKE = {COMPACT_STROKE};\n\n"
        + block("MASTER_CURVES", MASTER_COUNT, MASTER_SPAN)
        + "\n"
        + block("COMPACT_CURVES", COMPACT_COUNT, COMPACT_SPAN)
    )


def write(rel: str, text: str) -> None:
    p = ROOT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    print(f"wrote {rel}")


def png(rel: str, markup: str, size: int) -> None:
    p = ROOT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    cairosvg.svg2png(bytestring=markup.encode(), write_to=str(p),
                     output_width=size, output_height=size)
    print(f"wrote {rel} ({size}px)")


if __name__ == "__main__":
    write("public/icons/logo.svg", svg(MASTER_COUNT, MASTER_SPAN, MASTER_STROKE, uid="m", ground=False))
    write("public/favicon.svg", svg(COMPACT_COUNT, COMPACT_SPAN, COMPACT_STROKE, uid="f", ground=False))
    write("src/components/markGeometry.generated.ts", ts())

    plated = svg(COMPACT_COUNT, COMPACT_SPAN, COMPACT_STROKE, uid="p", ground=True, scale=0.88)
    png("public/icons/icon-192.png", plated, 192)
    png("public/icons/icon-512.png", plated, 512)
    # Maskable: the mark pulled into the 80% safe circle, ground bleeding out.
    png("public/icons/icon-maskable-512.png",
        svg(COMPACT_COUNT, COMPACT_SPAN, COMPACT_STROKE, uid="k", ground=True, scale=0.62), 512)
