"""
Localized (Madrid / Spain) crisis & harm-reduction resources, transcribed
verbatim from the spec docs (docs 3, 6, 8, 15, 16). These are static,
server-owned content — never generated by the LLM — so they cannot drift
or be "softened" by a model.

IMPORTANT: verify these phone numbers / services are still current before
any real-world use. They were current as documented in the source specs
but this app does not re-verify them at runtime.
"""

CRISIS_RESOURCES = [
    {"name": "Línea 024", "description": "Atención a la conducta suicida (24h, España)", "contact": "024"},
    {"name": "112", "description": "Emergencias", "contact": "112"},
    {
        "name": "Centro Sanitario Sandoval",
        "description": "Salud sexual, Madrid",
        "contact": "https://www.comunidad.madrid/hospital/sandoval",
    },
    {
        "name": "Red CAD",
        "description": "Centros de Atención a las Adicciones, Madrid Salud (Ayuntamiento de Madrid)",
        "contact": "https://www.madrid.es/portales/munimadrid/es/Inicio/Salud/Adicciones",
    },
    {"name": "Apoyo Positivo", "description": "Apoyo en salud sexual y chemsex", "contact": "https://apoyopositivo.org"},
    {"name": "Imagina MÁS", "description": "Salud sexual y comunitaria LGTBI+", "contact": "https://imaginamas.org"},
    {"name": "COGAM (programa ChemSex)", "description": "Colectivo LGTB+ de Madrid", "contact": "https://cogam.es"},
    {
        "name": "Energy Control",
        "description": "Información y análisis sobre drogas (incl. Chem-Safe)",
        "contact": "https://energycontrol.org",
    },
]

# Exact copy from doc 16 (Nivel 4 - variant when context is chemsex/consumption)
CRISIS_RESOURCES_CHEMSEX_VARIANT = [
    {"name": "112", "description": "Emergencias", "contact": "112"},
    {"name": "Línea 024", "description": "Atención a la conducta suicida", "contact": "024"},
    {
        "name": "Centro Sanitario Sandoval / Red CAD",
        "description": "Según disponibilidad",
        "contact": "ver recursos",
    },
]

# ----------------------------------------------------------------------
# Exact, server-owned message templates (doc 15 & doc 16). The LLM may
# only add a short warm sentence around these; it must never rewrite them.
# ----------------------------------------------------------------------

LEVEL4_PATIENT_MESSAGE = (
    "Detectamos que puedes estar pasando por un momento de mucho sufrimiento.\n\n"
    "Por favor, contacta ahora mismo con ayuda profesional:\n"
    "• Línea 024 (atención a la conducta suicida)\n"
    "• 112 (emergencias)\n\n"
    "No estás solo. Puedo quedarme aquí contigo mientras haces la llamada."
)

LEVEL4_PATIENT_MESSAGE_SECONDARY = (
    "Si estás en peligro inmediato, llama al 112.\n"
    "Si necesitas hablar con alguien especializado en conducta suicida, llama al 024.\n"
    "Estoy aquí mientras contactas con ellos."
)

LEVEL4_PATIENT_MESSAGE_CHEMSEX_VARIANT = (
    "Si estás en una crisis de consumo o te sientes fuera de control, contacta ahora con:\n"
    "• 112\n"
    "• Línea 024\n"
    "• Centro Sanitario Sandoval / Red CAD (según disponibilidad)\n\n"
    "Tu seguridad es lo primero."
)

LEVEL3_PATIENT_MESSAGE = (
    "Hemos detectado una variación importante en tu ritmo de los últimos días.\n\n"
    "No significa que estés en peligro inmediato, pero sí que puede ser buen momento "
    "para cuidarte con más atención.\n\n"
    "Puedes usar la Metáfora de la Ola o revisar tu plan de seguridad."
)

LEVEL3_PATIENT_MESSAGE_WITH_PROFESSIONAL = (
    LEVEL3_PATIENT_MESSAGE + "\n\nTu profesional de referencia ha sido informado para que pueda acompañarte mejor."
)

LEVEL3_PROFESSIONAL_NOTIFICATION_TEMPLATE = (
    "Alerta Nivel 3 – Desviación estructural\n"
    "Paciente: {patient_label}\n"
    "structural_score en banda inestable.\n"
    "Se adjunta resumen de tendencias de los últimos 14 días.\n"
    "Requiere revisión cuando te sea posible."
)

LEVEL4_PROFESSIONAL_NOTIFICATION_TEMPLATE = (
    "ALERTA NIVEL 4 – EMERGENCIA\n"
    "Paciente: {patient_label}\n"
    "Posible ideación activa o crisis grave.\n"
    "Se ha mostrado al paciente redirección a 024 y 112.\n"
    "Requiere atención inmediata."
)

# Techniques that must NEVER be suggested to this population (doc 3 & 8):
# TIPP "T" component (cold/pain-based grounding) — ice on face, ice-water
# immersion, rubber-band snapping, or any other self-harm-adjacent
# sensation. Safe alternatives only.
FORBIDDEN_TECHNIQUES = [
    "hielo en la cara",
    "inmersión en agua helada",
    "gomas elásticas",
    "dolor físico como técnica de grounding",
]

SAFE_GROUNDING_ALTERNATIVES = [
    "Sostener un objeto con textura marcada (p. ej. una piedra, tela rugosa)",
    "Presionar los pies con fuerza contra el suelo",
    "Un sabor intenso pero seguro (cítrico, menta fuerte)",
    "Respiración de suspiro fisiológico (inhalación doble por nariz + exhalación larga por boca)",
]
